# Generated by Django 4.0.5 on 2022-06-26 15:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_body_homepage_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=True))])))]))], null=True, use_json_field=None),
        ),
    ]
