# Generated by Django 4.0.5 on 2022-06-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_socialmediasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header',
        ),
    ]
