# Generated by Django 4.0.5 on 2022-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_carousel_homepagecarouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
