# Generated by Django 4.0.5 on 2022-07-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_headerlinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderLinks',
        ),
    ]
